#pragma once

#define WARN_01 "Didn't initialize variable"
#define WARN_02 "The label name was duplicated. please change the label name."
#define WARN_03 "Invalid use of IO. IO variable cannot be put in this line."
#define WARN_04 "Faild to operate math symbol. Please check argument and format."
#define WARN_05 "Faild to operate relational symbol. Please check argument and format."
#define WARN_06 "Faild to operate logic symbol. Please check argument and format."
#define WARN_07 "Faild to allocate arrary variable. Please check argument or format."
#define WARN_08 "Faild to define use of function. Please check argument or format."
#define WARN_09 "Check allocation size or a value between []."
#define WARN_10 "Assigned INT value may be not appropriate. Check the data type or over/underflow."
#define WARN_11 "Assigned UNIT value may be not appropriate. Check the data type or over/underflow."
#define WARN_12 "Assigned FLOAT value may be not appropriate. Check the data type or over/underflow."
#define WARN_13 "Assigned value may be not appropriate in DIM. Check the data type or over/underflow."

#define RTERR_01 "Current line is at the end of line."
#define RTERR_02 "Invalid speed range."
#define RTERR_03 "Invalid rotate axis value."
#define RTERR_04 "Invalid gripper value."
#define RTERR_05 "Invalid gripper value."
#define RTERR_06 "Invalid drive value"
#define RTERR_07 "Abnormal runtim error. The program can't be run."
#define RTERR_08 "Invalud let command format. Please check the grammer of LET command"
#define RTERR_09 "Jump label couldn't be found in GOSUB command."

#define CTERR_01 "Invalid label name or can't assign to the variable ."
#define CTERR_02 "Missing brace character { or }"
#define CTERR_03 "Missing brace character [ or ]"
#define CTERR_04 "Syntax error"
#define CTERR_05 "Unsupported symbol inserted. Syntax error."
#define CTERR_06 "Unassigned jump. The label couldn't find."
#define CTERR_07 "IF/ENDIF brace was opened. Close IF area."
#define CTERR_08 "ELSEIF couldn't be located after ELSE."
#define CTERR_09 "General syntax error."
#define CTERR_10 "Invalid RELEASE Command format. Failed to parse."
#define CTERR_11 "Invalid GRASP Command format. Failed to parse."
#define CTERR_12 "Invalid ROTATE Command format. Failed to parse."
#define CTERR_13 "Function name is already used. Change the function name."
#define CTERR_14 "Variable name is already used. Change the variable name."
#define CTERR_15 "Variable array variable name is already used. Change the array variable name."
#define CTERR_16 "Memory allocation vailed. Check array size or dimension."
#define CTERR_17 "Invalid input with STOP command."
#define CTERR_18 "Invalid use of ENDIF command."
#define CTERR_19 "Invalid use of WAIT command."
#define CTERR_20 "Failed to execute WAIT command."
#define CTERR_21 "Failed to initialize FOR command"
#define CTERR_22 "Failed to make decision within IF condition."
#define CTERR_23 "Failed to initialize SWITCH command"
#define CTERR_24 "Failed to jump in CASE command."
#define CTERR_25 "Couldn't find SWITCH command before this CASE was used."
#define CTERR_26 "Failed to use BREAK command. Couldn't exit SWITCH-CASE command."
#define CTERR_27 "Couldn't find label in GOTO command."
#define CTERR_28 "Fail to use math operators. Please check the use of math symbols."
#define CTERR_29 "Fail to use relational operators. Please check the use of relational symbols."
#define CTERR_30 "Fail to use logic operators. Please check the use of logical symbols."
#define CTERR_31 "Missing brace character ( or ). Invalid format."
#define CTERR_32 "Invalid format.Can't use T address with POSE data."
#define CTERR_33 "Invalid format.Can't use H address with POSE data."
#define CTERR_34 "The variable wasn't defined." 
#define CTERR_35 "Failed to run the DELAY command." 
#define CTERR_36 "Can't move to home position. Failed to run the HOME command." 
#define CTERR_37 "Can't use SPEED command. Invalid speed value." 
#define CTERR_38 "Failed to move robot. Invalid MOVE value or move range." 
#define CTERR_39 "Failed to drive robot. Invalid DRIVE value or drive range." 
#define CTERR_40 "Invalid math oeration between POSE data." 
#define CTERR_41 "Invalid POSE initialization. Internal POSE data can't be allocatable."
#define CTERR_42 "Wrong dimension initialization.A value is empty between[]."
#define CTERR_44 "Wrong dimension initialization.A value is zero between[]."
#define CTERR_43 "No value between ( and )."