#ifndef VREPEXTROBOTLANG_GLOBAL_H
#define VREPEXTROBOTLANG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VREPEXTROBOTLANG_LIBRARY)
#  define VREPEXTROBOTLANGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VREPEXTROBOTLANGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VREPEXTROBOTLANG_GLOBAL_H
